server:
  port: 5151
  servlet:
    context-path: /

spring:
  mvc:
    view:
      prefix: /WEB-INF/templates/
      suffix: .html
  jackson:
    default-property-inclusion: non_null
  data:
    mongodb:
      auto-index-creation: true

polymarket:
  privateKey: 0x0
  proxyAddress: 0x0
  chainId: 137
  api:
    url:
      gamma: https://gamma-api.polymarket.com/
      clob: https://clob.polymarket.com/

coins:
  events:
    btc:
      5m: true
      15m: false
      1h: false
      4h: false
      1d: false
    eth:
      5m: false
      15m: false
      1h: false
      4h: false
      1d: false
    sol:
      5m: false
      15m: false
      1h: false
      4h: false
      1d: false
    doge:
      5m: false
      15m: false
      1h: false
      4h: false
      1d: false
    hype:
      5m: false
      15m: false
      1h: false
      4h: false
      1d: false
    xrp:
      5m: false
      15m: false
      1h: false
      4h: false
      1d: false
    bnb:
      5m: false
      15m: false
      1h: false
      4h: false
      1d: false
